// <auto-generated />
namespace bizzart_proj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class simonchmo228 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(simonchmo228));
        
        string IMigrationMetadata.Id
        {
            get { return "201905310506008_simonchmo228"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
